### ISSUE TITLE
Facing Issue on IOS

### ISSUE THREAD

**Issue by abdelrahman-muntaser** [jaroslawkrol/vision-camera-realtime-object-detection#6]
I am trying to use this library with react-native-vision-camera, and after making pod install and trying to build the project
I am getting this error  9 duplicate symbols for architecture arm64

as i check these files coming for the tensorflow library it self,,
Is there a solution or a workaround for this

**package.json** 
  "react-native": "0.71.8",
  "react-native-reanimated": "^2.17.0",
  "react-native-vision-camera": "^2.15.4",

**Comment by byrizki** [comment]
it looks like this library can't be used with other library that depends on MLKit, it will causing this error
